version: "3.11"

services:
  backend:
    container_name: doyans
    image: backend:doyansbackendserver
    build:
      context: ./doyans
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./doyans:/user/src/app/ # create and copy build files
    ports:
      - 8000:8000 # mapping local computer to docker port
    env_file:
      - ./dev.env
    # depends_on:
  #     - database

  # database:
  #   image: postgres
  #   volumes:
  #     - ./data/db:
  #   ports:
  #     - 5432:5432
  #   env_file:
  #     - ./dev.env