version: "3.11"

services:
  app:
    container_name: doyans-backend
    image: backend:server
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code/ # create and copy build files
    ports:
      - '8000:8000' # mapping local computer to docker port
    env_file:
      - ./dev.env
    depends_on:
      - db

  db:
    container_name: doyans-db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./dev.env