version: "3.11"

services:
  doyans:
    container_name: doyansserver
    image: doyans:doyansbackendserver
    build:
    # django project
      context: ./doyans
    command: python manage.py runserver 0.0.0.0:8000 # run on container port
    volumes:
      - ./doyans:/user/src/app/ # create and copy build files
    ports:
      - 8000:8000 # mapping local computer to docker port
    environment: # environment variable
      - DEBUG = True # debug
      - SECRET_KEY = A234N4H2#$34dsfSD&*^NDAHD76757NK66jkhn567k$%^%$6jhjkjhhad7
      - ALLOWED_HOSTS = localhost, 127.0.0.1
